import "@/app/styles/_index.scss";
import { appTitle, cn } from "@/shared/libs";
import { Footer, Header, Sidebar } from "@/widgets";
import type { Metadata, Viewport } from "next";
import { ReactNode } from "react";
import { interFont } from "./fonts";

export const metadata: Metadata = {
  title: appTitle(),
  description: "Generated by create next app",
  alternates: {
    canonical: process.env.NEXT_PUBLIC_APP_META_CANONICAL,
  },
};

export const viewport: Viewport = {
  themeColor: "#141414",
  colorScheme: "light",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html className={cn("h-full !scroll-smooth", interFont.variable)} lang="ru">
      <body className="bg-app-clr-light text-app-clr-dark font-app-fm-inter h-full text-base font-normal antialiased rendering-speed">
        <div className="flex min-h-full flex-col overflow-hidden">
          <Header className="lg:hidden" />
          <div className="container flex-auto lg:pt-6">
            <div className="pb-28 lg:grid lg:grid-cols-[16rem_1fr] lg:gap-x-6">
              <Sidebar className="hidden lg:block" />
              <main id="main">{children}</main>
            </div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
